language: rust
sudo: false
cache: cargo

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - JOB=vulkan
        - CXX=g++-5
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - build-essentials
            - git
            - python
            - cmake
    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - JOB=metal
        - MACOSX_DEPLOYMENT_TARGET=10.9

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - |
    if [[ $JOB == "vulkan" ]]; then \
      cargo build --examples --features="vulkan" && \
      cargo build --examples --features="vulkan" --release; \
    fi
  - |
    if [[ $JOB == "metal" ]]; then \
      brew install cmake && \
      cargo build --examples --features="metal" && \
      cargo build --examples --features="metal" --release; \
    fi
  - cd book && mdbook build

deploy:
  provider: pages
  local-dir: target/book-output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  name: DocsBot
  verbose: true
  on:
    branch: master
