language: rust
sudo: false

cache:
  cargo

rust:
  - stable
  - beta
  allow_failures:
    - nightly

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cargo build --features="vulkan"
  - cargo build --features="vulkan" --release
  - cd book && mdbook build

deploy:
  provider: pages
  local-dir: target/book-output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  name: DocsBot
  verbose: true
  on:
    branch: master
