# The shaderc dependencies are already installed on the base images
# so we dont need to worry about installing them.
dist: xenial
os:
  - linux
  - osx
  #- windows # Waiting on https://travis-ci.community/t/timeout-before-install-step/1502/3
language: rust
rust:
  - stable
cache:
  cargo

before_script:
  - |
    [ $TRAVIS_OS_NAME = linux ] &&
    (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update) &&
    (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook) &&
    cargo install-update -a

script:
  - |
    [ $TRAVIS_OS_NAME = linux ] &&
    cargo build --examples --features="vulkan" &&
    cargo build --examples --features="vulkan" --release &&
    cd book &&
    mdbook build
  - |
    [ $TRAVIS_OS_NAME = osx ] &&
    cargo build --examples --features="metal" &&
    cargo build --examples --features="metal" --release

deploy:
  provider: pages
  local-dir: target/book-output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  name: DocsBot
  verbose: true
  on:
    branch: master
