cache:
  - C:\projects\learn-gfx-hal\target\debug\deps -> appveyor.yml
  - C:\projects\learn-gfx-hal\target\release\deps -> appveyor.yml

os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
# GNU
#    - channel: stable
#      target: x86_64-pc-windows-gnu
#    - channel: stable
#      target: i686-pc-windows-gnu
#    - channel: beta
#      target: x86_64-pc-windows-gnu
#    - channel: beta
#      target: i686-pc-windows-gnu
#    - channel: nightly
#      target: x86_64-pc-windows-gnu
#      #cargoflags: --features "unstable"
#    - channel: nightly
#      target: i686-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

# On advice of reptep we skip the build script and only use a test script
build: false

test_script:
  - cargo build --examples --features="vulkan"
  - cargo build --examples --features="vulkan" --release
  - cargo build --examples --features="dx12"
  - cargo build --examples --features="dx12" --release
